name: pointcept
channels:
  - pytorch
  - nvidia/label/cuda-12.1.66
  - nvidia
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cuda
  - conda-forge::cudnn
  - gcc=12.*
  - gxx=12.*
  - pytorch=2.5.0
  - torchvision=0.20.0
  - torchaudio=2.5.0
  - pytorch-cuda=12.1
  - ninja
  - google-sparsehash
  - h5py
  - pyyaml
  - tensorboard
  - tensorboardx
  - wandb
  - yapf
  - addict
  - einops
  - scipy
  - plyfile
  - termcolor
  - timm
  - ftfy
  - regex
  - tqdm
  - matplotlib
  - black
  - open3d
  - flash-attn==2.7.4.post1 # fit to ubuntu 20.04 with glibc 2.31
  - pip:
    - --find-links https://data.pyg.org/whl/torch-2.5.0+cu121.html
    - torch-cluster
    - torch-scatter
    - torch-sparse
    - torch-geometric
    - spconv-cu121
    - git+https://github.com/octree-nn/ocnn-pytorch.git
    - git+https://github.com/openai/CLIP.git
    - git+https://github.com/Dao-AILab/flash-attention.git
    - ./libs/pointops
    - ./libs/pointgroup_ops